spring:
  application:
    name: mspedido
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka
      instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
