spring.application.name=monolito

# --- DATABASE (Corrigido reWriteBatchedInserts) ---
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?reWriteBatchedInserts=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONNECTION POOL ---
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# --- HIBERNATE BATCH ---
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# --- JPA GENERAL ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- LOGS ---
spring.jpa.show-sql=false
spring.jpa.format_sql=false
spring.jpa.properties.hibernate.generate_statistics=false

# --- THREADS ---
spring.threads.virtual.enabled=true
server.tomcat.threads.max=200

